// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://shtbxnpauhbpihvxpxol.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNodGJ4bnBhdWhicGlodnhweG9sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2ODc1NTMsImV4cCI6MjA2NDI2MzU1M30.LqEfOZmirxxJKAXWoG0nHWQsvmar-wI6WkIVJsSJdQk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);